version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@chakra-ui/theme-tools"
    versions:
    - 1.0.3
    - 1.0.4
    - 1.1.0
    - 1.1.1
    - 1.1.2
    - 1.1.3
    - 1.1.4
    - 1.1.5
  - dependency-name: "@chakra-ui/utils"
    versions:
    - 1.1.0
    - 1.2.0
    - 1.3.0
    - 1.4.0
    - 1.5.0
    - 1.5.1
    - 1.5.2
    - 1.6.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: next-seo
    versions:
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.22.0
    - 4.23.0
